name: release

on:
  push:
    branches:
      - main
      - master

jobs:
  blocklet:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-upload: false
          skip-deploy: false
          skip-release: true
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
